title: Lucas Butzke's Projects
email: lucasbutzke@gmail.com
description: Here is a compilation of my experiences, stories and projects that I've worked for in my years of experiences.
url: https://lucasbutzke.github.io
baseurl: ""
github_username: lucasbutzke

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
