title: Personal projects blog
email: lucasbutzke@gmail.com
description: My personal homepage and projects blog.
url: https://lucasbutzke.github.io
baseurl: ""
github_username: lucasbutzke

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
